name: w2019
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: ping <andre.lipke@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  tuple: any
  uuid: any
  mime: any
  crypto: ^2.1.3
  vector_math: any
  xml: any
  font_face_observer: any
#  path: ^1.6.0

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0

transformers:
  - $dart2js:
    minify: false